site_name: MarketWatch API

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - mkdocstrings
  - search

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Explanation: explanation.md
  - Examples: examples.md
  - API Reference: api.md
  - Reference: reference.md
  - Contacts: contacts.md