openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: http://localhost:5003
paths:
  /.well-known/ai-plugin.json:
    get:
      operationId: plugin_manifest__well_known_ai_plugin_json_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Plugin Manifest
  /generate_diagram/{diagram_type}:
    post:
      operationId: generate_diagram_endpoint_generate_diagram__diagram_type__post
      parameters:
      - in: path
        name: diagram_type
        required: true
        schema:
          title: Diagram Type
          type: string
      - in: query
        name: input_file
        required: false
        schema:
          title: Input File
          type: string
      - in: query
        name: output_file
        required: false
        schema:
          title: Output File
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Generate Diagram Endpoint Generate Diagram  Diagram
                  Type  Post
                type: object
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Generate Diagram Endpoint
  /generate_text/{prompt}:
    get:
      operationId: generate_text_endpoint_generate_text__prompt__get
      parameters:
      - in: path
        name: prompt
        required: true
        schema:
          title: Prompt
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                title: Response Generate Text Endpoint Generate Text  Prompt  Get
                type: object
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Generate Text Endpoint
  /logo.png:
    get:
      operationId: plugin_logo_logo_png_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Plugin Logo
  /openapi.yaml:
    get:
      operationId: openapi_spec_openapi_yaml_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Openapi Spec

components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
