name: Python application test with FastAPI and Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run tests with pytest
      run: |
        python -m pytest
    
    - name: Run App with timeout
      run: |
        # Start the app in the background
        python app.py &
        APP_PID=$!
        
        # Wait for 1 minutes (60 seconds)
        sleep 60
        
        # Check if the process is still running and kill it if it is
        if ps -p $APP_PID > /dev/null; then
          echo "Application is still running after 10 minutes, terminating..."
          kill $APP_PID
        else
          echo "Application has already terminated."
        fi
        
        # Wait for the process to terminate
        wait $APP_PID || true
        
        echo "Application run completed."
